# Generated by Django 5.0.4 on 2025-01-31 23:56

import django.db.models.deletion
import publish_articles.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título del artículo', max_length=100, validators=[publish_articles.models.validate_title_length])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('written', models.TextField()),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(blank=True, max_length=5000)),
                ('image', models.CharField(blank=True, max_length=5000)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la etiqueta', max_length=100, unique=True)),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('color', models.CharField(help_text='Color de la etiqueta en formato HEX', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagDetailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_saved', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_details', to='publish_articles.articulomodel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_details', to='publish_articles.tagmodel')),
            ],
            options={
                'verbose_name': 'Detalle de Etiqueta',
                'verbose_name_plural': 'Detalles de Etiquetas',
                'db_table': 'tags_detail',
                'ordering': ['-article__created_at'],
                'unique_together': {('article', 'tag')},
            },
        ),
    ]
