# Generated by Django 5.0.4 on 2025-02-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagdetailmodel',
            options={'verbose_name': 'Detalle de Tag', 'verbose_name_plural': 'Detalles de Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='tagdetailmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_details', to='publish_articles.tagmodel'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
